// User Specific

export const OTP_REQUESTED = 'OTP_REQUESTED';
export const OTP_SUCCESS = 'OTP_SUCCESS';
export const OTP_FAILED = 'OTP_FAILED';

export const OTP_VERIFICATION_REQUESTED = 'OTP_VERIFICATION_REQUESTED';
export const OTP_VERIFICATION_SUCCESS = 'OTP_VERIFICATION_SUCCESS';
export const OTP_VERIFICATION_FAILED = 'OTP_VERIFICATION_FAILED';

// Company Specific

export const COMPANIES_LIST_REQUESTED = 'COMPANIES_LIST_REQUESTED';
export const COMPANIES_LIST_SUCCESS = 'COMPANIES_LIST_SUCCESS';
export const COMPANIES_LIST_FAILED = 'COMPANIES_LIST_FAILED';

export const CHANGE_COMPANY = 'CHANGE_COMPANY';

export const COMPANY_AUTH_REQUESTED = 'COMPANY_AUTH_REQUESTED';
export const COMPANY_AUTH_SUCCESS = 'COMPANY_AUTH_SUCCESS';
export const COMPANY_AUTH_FAILED = 'COMPANY_AUTH_FAILED';

export const COMPANY_MEMBERS_REQUESTED = 'COMPANY_MEMBERS_REQUESTED';
export const COMPANY_MEMBERS_SUCCESS = 'COMPANY_MEMBERS_SUCCESS';
export const COMPANY_MEMBERS_FAILED = 'COMPANY_MEMBERS_FAILED';

export const ACCOUNTS_NAME = 'ACCOUNTS_NAME';

// Items Specific

export const COMPANY_ITEMS_REQUESTED = 'COMPANY_ITEMS_REQUESTED';
export const COMPANY_ITEMS_SUCCESS = 'COMPANY_ITEMS_SUCCESS';
export const SHOW_ITEM_GROUP_DIALOG = 'SHOW_ITEM_GROUP_DIALOG';
export const COMPANY_ITEMS_FAILED = 'COMPANY_ITEMS_FAILED';
export const TOGGLE_ADD_ITEMS = 'TOGGLE_ADD_ITEMS';
export const SET_ITEM_GROUP = 'SET_ITEM_GROUP';
export const UPDATE_SELECTED_ITEM_GROUP = 'UPDATE_SELECTED_ITEM_GROUP';
export const RESET_SELECTED_ITEM_GROUP = 'RESET_SELECTED_ITEM_GROUP;';
export const SET_ALL_ITEM_GROUP = 'SET_ALL_ITEM_GROUP';
export const SET_ITEM_PAYLOAD = 'SET_ITEM_PAYLOAD';
export const SHOW_ITEM_SALES_PRICE = 'SHOW_ITEM_SALES_PRICE';
export const CANCEL_ITEM_SALES_PRICE = 'CANCEL_ITEM_SALES_PRICE';
export const RESET_ITEM_PAYLOAD = 'RESET_ITEM_PAYLOAD';
export const SET_ITEM_GROUP_SEARCH_TEXT = 'SET_ITEM_GROUP_SEARCH_TEXT';
export const SHOW_SALES_PRICE_VALUE = 'SHOW_SALES_PRICE_VALUE';
export const GET_BRANCHS = 'GET_BRANCHS';
export const SET_ITEM_DATA = 'SET_ITEM_DATA';

// Vouchers Specific

export const FETCH_UNPAID_VOUCHERS_SUCCESS = 'FETCH_UNPAID_VOUCHERS_SUCCESS';
export const FETCH_UNPAID_VOUCHERS_FAILURE = 'FETCH_UNPAID_VOUCHERS_FAILURE';
export const VOUCHER_DATE = 'VOUCHER_DATE';
export const VOUCHERS_LIST_REQUESTED = 'VOUCHERS_LIST_REQUESTED';
export const VOUCHERS_LIST_SUCCESS = 'VOUCHERS_LIST_SUCCESS';
export const SAVED_VOUCHER_SUCCESS = 'SAVED_VOUCHER_SUCCESS';
export const VOUCHERS_LIST_FAILED = 'VOUCHERS_LIST_FAILED';
export const SET_VOUCHER_TYPE = 'SET_VOUCHER_TYPE';

export const GET_VOUCHER_REQUESTED = 'GET_VOUCHER_REQUESTED';
export const GET_VOUCHER_SUCCESS = 'GET_VOUCHER_SUCCESS';
export const GET_VOUCHER_FAILED = 'GET_VOUCHER_FAILED';

export const INCREMENT_VOUCHER_REQUESTED = 'INCREMENT_VOUCHER_REQUESTED';
export const INCREMENT_VOUCHER_SUCCESS = 'INCREMENT_VOUCHER_SUCCESS';
export const INCREMENT_VOUCHER_FAILED = 'INCREMENT_VOUCHER_FAILED';

export const GENERATE_VOUCHER_PDF_REQUESTED = 'GENERATE_VOUCHER_PDF_REQUESTED';
export const GENERATE_VOUCHER_PDF_SUCCESS = 'GENERATE_VOUCHER_PDF_SUCCESS';
export const GENERATE_VOUCHER_PDF_FAILED = 'GENERATE_VOUCHER_PDF_FAILED';

// Contact Specific

export const ADD_CONTACT_DATA_REQUEST = 'ADD_CONTACT_DATA_REQUEST';
export const TOGGLE_OPEN_ADD_CONTACT = 'TOGGLE_OPEN_ADD_CONTACT';
export const ADD_CONTACT_DATA_SUCCESSS = 'ADD_CONTACT_DATA_SUCCESSS';
export const ADD_CONTACT_DATA_FAILED = 'ADD_CONTACT_DATA_FAILED';
export const CONTACT_LIST_FAILED = 'CONTACT_LIST_FAILED';
export const CONTACT_LIST_SUCCESS = 'CONTACT_LIST_SUCCESS';
export const CHECK_FOR_NAME_FAILED = 'CHECK_FOR_NAME_FAILED';
export const COMPANY_BRANCH_FAILURE = 'COMPANY_BRANCH_FAILURE';
export const COMPANY_BRANCH_SUCCESS = 'COMPANY_BRANCH_SUCCESS';
export const CONTACT_LIST_REQUESTED = 'CONTACT_LIST_REQUESTED';
export const CHECK_FOR_NAME_SUCCESS = 'CHECK_FOR_NAME_SUCCESS';
export const UPDATE_CONTACT_SUCCESS = 'UPDATE_CONTACT_SUCCESS';
export const UPDATE_CONTACT_FAILED = 'UPDATE_CONTACT_FAILED';
export const ADD_CONTACT_NAME_FAILED = 'ADD_CONTACT_NAME_FAILED';
export const COMPANY_BRANCH_REQUESTED = 'COMPANY_BRANCH_REQUESTED';
export const ADD_CONTACT_NAME_REQUEST = 'ADD_CONTACT_NAME_REQUEST';
export const ADD_CONTACT_NAME_SUCCESS = 'ADD_CONTACT_NAME_SUCCESS';
export const UPDATE_CONTACT_NAME_FAILED = 'UPDATE_CONTACT_NAME_FAILED';
export const UPDATE_CONTACT_NAME_SUCCESS = 'UPDATE_CONTACT_NAME_SUCCESS';
export const PARTY_STATEMENT_SUCCESS = 'PARTY_STATEMENT_SUCCESS';
export const PARTY_STATEMENT_FAILED = 'PARTY_STATEMENT_FAILED';

// Purchase Vouchers Specific
export const UPDATE_BUSINESS_CONTACT = 'UPDATE_BUSINESS_CONTACT';
export const POPULATE_ADDTIONAL_DISCOUNT = 'POPULATE_ADDTIONAL_DISCOUNT';
export const POPULATE_OTHER_CHARGES = 'POPULATE_OTHER_CHARGES';
export const TOGGLE_SHIPPING_DETAILS_LINK = 'TOGGLE_SHIPPING_DETAILS_LINK';
export const TOGGLE_PURCHASE_SALES_DRAWER = 'TOGGLE_PURCHASE_SALES_DRAWER';
export const UPDATE_SHIPPING_FOR_SELECTED_VOUCHER = 'UPDATE_SHIPPING_FOR_SELECTED_VOUCHER';

export const RESET_VOUCHER_DETAILS = 'RESET_VOUCHER_DETAILS';
export const RESET_TRANSPORT_DETAILS = 'RESET_TRANSPORT_DETAILS';
export const RESET_LINE_ITEMS_DETAILS = 'RESET_LINE_ITEMS_DETAILS';
export const RESET_ADDTIONAL_DISCOUNT = 'RESET_ADDTIONAL_DISCOUNT';
export const UPDATE_VOUCHER_NO = 'UPDATE_VOUCHER_NO';
export const UPDATE_DATE = 'UPDATE_DATE';
export const UPDATE_VOUCHERS_DETAILS_ACCOUNTS = 'UPDATE_VOUCHERS_DETAILS_ACCOUNTS';

export const UPDATE_SHIPPING_ADDRESS = 'UPDATE_SHIPPING_ADDRESS';
export const ON_HIDE_SHOW_LINK = 'ON_HIDE_SHOW_LINK';
export const FETCH_VOUCHERS_DATA = 'FETCH_VOUCHERS_DATA';
export const SET_SELECTED_VOUCHER_ID = 'SET_SELECTED_VOUCHER_ID';
export const UPDATE_PIN_CODE = 'UPDATE_PIN_CODE';
export const UPDATE_CITY = 'UPDATE_CITY';
export const UPDATE_STATE = 'UPDATE_STATE';
export const SET_SHIPPING_ADDRESS = 'SET_SHIPPING_ADDRESS';

export const LINE_ITEM_INDEX = 'LINE_ITEM_INDEX';
export const ADD_NEW_LINE_ITEM = 'ADD_NEW_LINE_ITEM';
export const SET_CURRENT_ITEM_TO_FOCUS = 'SET_CURRENT_ITEM_TO_FOCUS';
export const UPDATE_LINE_ITEM_NAME = 'UPDATE_LINE_ITEM_NAME';
export const UPDATE_LINE_ITEM = 'UPDATE_LINE_ITEM';
export const VIEW_TAX_ANALYSIS = 'VIEW_TAX_ANALYSIS';
export const UPDATE_TEMP_ITEM = 'UPDATE_TEMP_ITEM';
export const UPDATE_LINE_ITEM_FIELD = 'UPDATE_LINE_ITEM_FIELD';
export const DISCOUNT_CHANGE = 'DISCOUNT_CHANGE';
export const DELETE_LINE_ITEM = 'DELETE_LINE_ITEM';
export const HANDLE_ITEM_CALCULATIONS = 'HANDLE_ITEM_CALCULATIONS';
export const UPDATE_TAX_BRACKUP = 'UPDATE_TAX_BRACKUP';
export const UPDATE_CURRENT_BALANCE = 'UPDATE_CURRENT_BALANCE';
export const UPDATE_ALL_BRANCHES = 'UPDATE_ALL_BRANCHES';
export const ON_CLOSE_VOUCHER_PICKER = 'ON_CLOSE_VOUCHER_PICKER';

export const UPDATE_NARRATION = 'UPDATE_NARRATION';
export const CLOSE_BUSINESS_CARD = 'CLOSE_BUSINESS_CARD';

export const ADD_LINE = 'ADD_LINE';
export const UPDATE_ACCOUNT_FIELD = 'UPDATE_ACCOUNT_FIELD';
export const UPDATE_FILTERED_NAMES = 'UPDATE_FILTERED_NAMES';
export const UPDATE_CHARGES = 'UPDATE_CHARGES';
export const DELETE_CHRAGES = 'DELETE_CHRAGES';
export const DELETE_OTHER_CHRAGES_AFTER_TAX = 'DELETE_OTHER_CHRAGES_AFTER_TAX';

export const TOGGLE_ADD_DISCOUNT = 'TOGGLE_ADD_DISCOUNT';
export const HIDE_SHIPPING_DETAILS = 'HIDE_SHIPPING_DETAILS';
export const SET_DISCOUNT_UNITS = 'SET_DISCOUNT_UNITS';
export const SET_DISCOUNT_VALUE = 'SET_DISCOUNT_VALUE';
export const RESET_ADD_DISCOUNT = 'RESET_ADD_DISCOUNT';

export const DRAWER_OPEN_ADD_ACCOUNTS = 'DRAWER_OPEN_ADD_ACCOUNTS';
export const ON_FOCUS_CURRENT_INDEX = 'ON_FOCUS_CURRENT_INDEX';

export const SET_ROUND_OFF_VALUE = 'SET_ROUND_OFF_VALUE';

export const TOGGLE_OTHER_CHARGES = 'ADD_NEW_CHARGES';
export const CURRENT_CHARGE_INDEX_FOCUS = 'CURRENT_CHARGE_INDEX_FOCUS';
export const CURRENT_OTHER_CHARGES_AFTER_TAX_INDEX_FOCUS =
  'CURRENT_OTHER_CHARGES_AFTER_TAX_INDEX_FOCUS';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const UPDATE_SELECTED_VOUCHER = 'UPDATE_SELECTED_VOUCHER';
export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_FAILED = 'FETCH_FAILED';
export const POPULATE_ACCOUNTS_SUGGESTION = 'POPULATE_ACCOUNTS_SUGGESTION';
export const UPDATE_AMOUNT = 'UPDATE_AMOUNT';
export const DELETE_CHARGES = 'DELETE_CHARGES';
export const UPDATE_TRANSPORT_DETAILS = 'UPDATE_TRANSPORT_DETAILS';

export const ON_HIDE_OTHER_CHARGES = 'ON_HIDE_OTHER_CHARGES';
export const ADD_OTHER_CHARGES_NEW_LINE = 'ADD_OTHER_CHARGES_NEW_LINE';
export const ON_HIDE_OTHER_CHARGES_AFTER_TAX = 'ON_HIDE_OTHER_CHARGES_AFTER_TAX';
export const RESET_VOUCHER_LINE_ITEMS = 'RESET_VOUCHER_LINE_ITEMS';
export const ADD_OTHER_CHARGES_AFTER_TAX_NEW_LINE = 'ADD_OTHER_CHARGES_AFTER_TAX_NEW_LINE';
export const GET_BRANCH_SUCCESS = 'GET_BRANCH_SUCCESS';
export const GET_BRANCH_FAILED = 'GET_BRANCH_FAIL';
export const BRANCH_SEARCH_TEXT = 'BRANCH_SEARCH_TEXT';
export const HANDLE_TRANSPORT_DONE = 'HANDLE_TRANSPORT_DONE';
export const HANDLE_VOUCHER_DETAILS_DONE = 'HANDLE_VOUCHER_DETAILS_DONE';
export const RESET_SHIPPING_DETAILS = 'RESET_SHIPPING_DETAILS';
export const UPDATE_LINE_ITEM_CRDR = 'UPDATE_LINE_ITEM_CRDR';
export const FETCH_VOUCHER_BY_NUMBER_SUCCESS = 'FETCH_VOUCHER_BY_NUMBER_SUCCESS';
export const FETCH_VOUCHER_BY_NUMBER_FAILURE = 'FETCH_VOUCHER_BY_NUMBER_FAILURE';

//purchaseVoucherList specific
export const FETCH_VOUCHER_SUCCESSED = ' FETCH_VOUCHER_SUCCESSED,';
export const FETCH_VOUCHER_FAILED = 'FETCH_VOUCHER_FAILED,';

export const UPDATE_PARTY_NAME = 'UPDATE_PARTY_NAME';
// reports
export const FETCH_TRIAL_BALANCE_SUCCESS = 'FETCH_TRIAL_BALANCE_SUCCESS';
export const FETCH_TRIAL_BALANCE_FAIL = 'FETCH_TRIAL_BALANCE_FAIL';
export const SHOW_DETAIL_VIEW = 'SHOW_DETAIL_VIEW';
export const SET_ROUTES_DETAILS = 'SET_ROUTES_DETAILS';
export const SET_ROUTING_STATUS = 'SET_ROUTING_STATUS';
export const SET_GROUP_DETAILS = 'SET_GROUP_DETAILS';
export const GET_DATE_RANGE = 'GET_DATE_RANGE';
export const SHOW_LEDGER_VIEW = 'SHOW_LEDGER_VIEW';
export const SET_LEDGER_DETAILS = 'SET_LEDGER_DETAILS';
export const RESET_TO_TRIAL_HOME = 'RESET_TO_TRIAL_HOME';
export const SHOW_YEARLY_VIEW = 'SHOW_YEARLY_VIEW';
export const SET_YEARLY_DETAILS = 'SET_YEARLY_DETAILS';
export const SHOW_MONTHLY_VIEW = 'SHOW_MONTHLY_VIEW';
export const SHOW_PERIOD_DIALOG = 'SHOW_PERIOD_DIALOG';
export const CHANGE_DATE_RANGE = 'CHANGE_DATE_RANGE';
export const SET_ITEM_ERROR = 'SET_ITEM_ERROR';
